name: general_dev_server
description: A Library Full Package Template
version: 0.0.0 #general_dev_library
homepage: https://github.com/azkadev/general_dev
repository: https://github.com/azkadev/general_dev
issue_tracker: https://github.com/azkadev/general_dev/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - general_dev
#   - general_dev_flutter
#   - general_dev_dart
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
